#
# this file is a sites.yml file for development and testing modes
#
default:
  name: crabgrass
  domain: localhost
  email_sender: 'crabgrass-system@localhost'
  secret: '3d3dc74473a8a65696b564a4214b3'
  pagination_size: 29
  super_admin_group_id: 35
  translation_group: animals
  default_language:
  - en_US
  available_page_types:
  - Message
  - Discussion
  - Wiki
  - RateMany
  - RankedVote
  - TaskList
  - Asset
  - Gallery
  - ExternalVideo
  - Article
  tracking: true

