##
## In order of number of speakers worldwide
## http://en.wikipedia.org/wiki/Most_spoken_languages
##

zh:
  id: 1
  name: 中文
  code: zh

hi:
  id: 2
  name: हिंदी
  code: hi

es:
  id: 3
  name: Español
  code: es

en:
  id: 4
  name: English
  code: en

ar:
  id: 5
  name: العربية
  code: ar
  rtl: true

pt:
  id: 6
  name: Português
  code: pt

#7 = bengali

ru:
  id: 8
  name: Pyccĸий
  code: ru

#9 = japanese

de:
  id: 10
  name: Deutsch
  code: de

#11 = punjabi

sw:
  id: 12
  name: Kiswahili
  code: sw

#13 = wu
#14 = javanese
#15 = telugu
#16 = marathi
#17 = vietnamese
#18 = korean
#19 = tamil

fr:
  id: 20
  name: Français
  code: fr

it:
  id: 21
  name: Italiano
  code: it

tr:
  id: 24
  name: Türkçe
  code: tr

pl:
  id: 28
  name: Polski
  code: pl

el:
  id: 53
  name: Ελληνικά
  code: el

he:
  id: 78
  name: עִבְרִית
  code: he
  rtl: true

sv:
  id: 79
  name: Svenska
  code: sv

da:
  id: 104
  name: Dansk
  code: da


